# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!
import source_rc
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(826, 820)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 501, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_canerr = QtWidgets.QLabel(self.groupBox)
        self.label_canerr.setGeometry(QtCore.QRect(410, 50, 31, 20))
        self.label_canerr.setStyleSheet("border-image: url(:/Source/ok.jpg);\n"
"border-image: url(:/Source/error.jpg);")
        self.label_canerr.setText("")
        self.label_canerr.setObjectName("label_canerr")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(93, 18, 98, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(329, 50, 75, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(197, 17, 76, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(12, 17, 75, 23))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(93, 50, 98, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(329, 17, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(12, 50, 75, 20))
        self.label_2.setObjectName("label_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 17, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(410, 80, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 80, 75, 20))
        self.label_10.setObjectName("label_10")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(90, 80, 311, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_canok = QtWidgets.QLabel(self.groupBox)
        self.label_canok.setGeometry(QtCore.QRect(410, 50, 31, 21))
        self.label_canok.setStyleSheet("border-image: url(:/Source/ok.jpg);")
        self.label_canok.setText("")
        self.label_canok.setObjectName("label_canok")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 140, 501, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton.setGeometry(QtCore.QRect(10, 50, 111, 16))
        self.radioButton.setObjectName("radioButton")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(210, 20, 60, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 20, 133, 20))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(156, 20, 78, 20))
        self.label_8.setObjectName("label_8")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 20, 112, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.comboBox_5 = QtWidgets.QComboBox(self.widget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_5)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 230, 501, 191))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 100, 231, 51))
        self.groupBox_4.setObjectName("groupBox_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_3.setGeometry(QtCore.QRect(7, 20, 66, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_4.setGeometry(QtCore.QRect(79, 20, 65, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_4)
        self.comboBox_6.setGeometry(QtCore.QRect(150, 20, 66, 20))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 10, 231, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_4.setGeometry(QtCore.QRect(11, 21, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(92, 21, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(11, 51, 60, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_2.setGeometry(QtCore.QRect(77, 51, 133, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(270, 10, 201, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox.setGeometry(QtCore.QRect(20, 30, 171, 16))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_2.setGeometry(QtCore.QRect(20, 47, 171, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_3.setGeometry(QtCore.QRect(20, 64, 171, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_4.setGeometry(QtCore.QRect(20, 81, 171, 16))
        self.checkBox_4.setObjectName("checkBox_4")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_13.setGeometry(QtCore.QRect(40, 20, 75, 23))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_14.setGeometry(QtCore.QRect(140, 20, 75, 23))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_15.setGeometry(QtCore.QRect(40, 60, 75, 23))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_16.setGeometry(QtCore.QRect(140, 60, 75, 23))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_17.setGeometry(QtCore.QRect(40, 100, 75, 23))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_18.setGeometry(QtCore.QRect(140, 100, 75, 23))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_19.setGeometry(QtCore.QRect(40, 140, 75, 23))
        self.pushButton_19.setObjectName("pushButton_19")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "CAN State"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "PCAN_DNGBUS1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "PCAN_USBBUS1"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "PCAN_USBBUS2"))
        self.label_3.setText(_translate("Dialog", "CAN State"))
        self.pushButton.setText(_translate("Dialog", "Refresh"))
        self.label.setText(_translate("Dialog", "HardWare"))
        self.comboBox.setItemText(0, _translate("Dialog", "1 MBit/sec"))
        self.comboBox.setItemText(1, _translate("Dialog", "800 kBit/sec"))
        self.comboBox.setItemText(2, _translate("Dialog", "500 kBit/sec"))
        self.comboBox.setItemText(3, _translate("Dialog", "250 kBit/sec"))
        self.comboBox.setItemText(4, _translate("Dialog", "125 kBit/sec"))
        self.comboBox.setItemText(5, _translate("Dialog", "100 kBit/sec"))
        self.pushButton_2.setText(_translate("Dialog", "Initialize"))
        self.label_2.setText(_translate("Dialog", "Baudrate"))
        self.pushButton_3.setText(_translate("Dialog", "Release"))
        self.pushButton_7.setText(_translate("Dialog", "ChooseFile"))
        self.label_10.setText(_translate("Dialog", "ConfigFile"))
        self.groupBox_2.setTitle(_translate("Dialog", "State Control"))
        self.radioButton.setText(_translate("Dialog", "OpenDriverDoor"))
        self.label_8.setText(_translate("Dialog", "Vehicle Speed"))
        self.label_9.setText(_translate("Dialog", "PowerKey"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "Off"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "Acc"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "Run"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "Crank"))
        self.groupBox_4.setTitle(_translate("Dialog", "Set Warning icon"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Zone1"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Zone2"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Zone3"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "Zone4"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Zone1"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Zone2"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Zone3"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "Zone4"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "Zone1"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "Zone2"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "Zone3"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "Zone4"))
        self.groupBox_3.setTitle(_translate("Dialog", "Set Guideline"))
        self.pushButton_4.setText(_translate("Dialog", "GL_Left"))
        self.pushButton_5.setText(_translate("Dialog", "GL_Right"))
        self.label_4.setText(_translate("Dialog", "Set_GL_Val"))
        self.groupBox_7.setTitle(_translate("Dialog", "Set Text"))
        self.checkBox.setText(_translate("Dialog", "RVC Unavailable"))
        self.checkBox_2.setText(_translate("Dialog", "Guideline Unavailable"))
        self.checkBox_3.setText(_translate("Dialog", "No Guideline"))
        self.checkBox_4.setText(_translate("Dialog", "Park Symbol Unavailable"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "RVC ON"))
        self.pushButton_13.setText(_translate("Dialog", "Phone"))
        self.pushButton_14.setText(_translate("Dialog", "Mute"))
        self.pushButton_15.setText(_translate("Dialog", "Vol +"))
        self.pushButton_16.setText(_translate("Dialog", "Vol -"))
        self.pushButton_17.setText(_translate("Dialog", "Previous"))
        self.pushButton_18.setText(_translate("Dialog", "Next"))
        self.pushButton_19.setText(_translate("Dialog", "SRC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "SWC"))


